name = "hugo-dusk"
license = "MIT"
licenselink = "https://github.com/gyorb/hugo-dusk/blob/master/LICENSE.md"
description = "A minimalistic dark responsive theme."
homepage = "https://github.com/gyorb/hugo-dusk"
tags = ["blog", "responsive", "google analytics", "disqus", "utterances", "syntax highlighting", "custom themes", "minimal", "minimalist", "clean", "dark"]
features = ["blog"]
min_version = "0.146.0"

[author]
  name = "Gyorgy Orban"
  homepage = "https://github.com/gyorb"
