baseurl = "/"
title = "Hugo Themes"
copyright = "Copyright (c) 2008 - 2014, all rights reserved."
languageCode = "en-US"
canonifyurls = true
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[author]
  name = ""

[params.meta]
  keywords = ""
  description = "Personal blog."

[params]
  email = "myemail"
  github = "github id"
  #gitlab = "gitlab id"
  twitter = "twitter id"
  #linkedin = "linkedin id"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
