baseurl = "/"
title = "Hugo Themes"
copyright = "Copyright (c) 2008 - 2014, all rights reserved."
languageCode = "en-US"
canonifyurls = true
paginate = 3
theme = "hugo-dusk"
themesDir = "../.."
enableRobotsTXT = true

googleAnalytics = ""
disqusShortname = ""

SectionPagesMenu = "main"

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[taxonomies]
  category = "categories"
  group = "groups"
  series = "series"
  tag = "tags"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "gruvbox"  # dark themes: monokai, api, fruity, native, rrt, swapoff ... https://xyproto.github.io/splash/docs/longer/all.html

[params.author]
  name = ""

[params.meta]
  keywords = ""
  description = "Personal blog."
[params.meta.fediverse]
  creator = "@username@mastodon.server" # https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/

[params]
  email = "myemail"
  github = "github id"
  #gitlab = "gitlab id"
  twitter = "twitter id"
  #linkedin = "linkedin id"
  theme_colors = "default-dark"

[params.mastodon] # https://joinmastodon.org/verification
  username = "username"
  server = "https://example.com"
